### ISSUE TITLE
Outsider on Ubuntu 18.04

### ISSUE THREAD

**Issue by magjo67** [jonathanunderwood/outsider#14]
# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.1 LTS
Release:        18.04
Codename:       bionic

# python3 setup.py install
running install
running bdist_egg
running egg_info
writing outsider.egg-info/PKG-INFO
writing dependency_links to outsider.egg-info/dependency_links.txt
writing entry points to outsider.egg-info/entry_points.txt
writing requirements to outsider.egg-info/requires.txt
writing top-level names to outsider.egg-info/top_level.txt
writing manifest file 'outsider.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
copying outsider/version.py -> build/lib/outsider
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/blackstarid
copying build/lib/blackstarid/blackstarid.py -> build/bdist.linux-x86_64/egg/blackstarid
copying build/lib/blackstarid/__init__.py -> build/bdist.linux-x86_64/egg/blackstarid
creating build/bdist.linux-x86_64/egg/outsider
copying build/lib/outsider/__main__.py -> build/bdist.linux-x86_64/egg/outsider
copying build/lib/outsider/version.py -> build/bdist.linux-x86_64/egg/outsider
copying build/lib/outsider/outsider.py -> build/bdist.linux-x86_64/egg/outsider
copying build/lib/outsider/outsider.ui -> build/bdist.linux-x86_64/egg/outsider
copying build/lib/outsider/__init__.py -> build/bdist.linux-x86_64/egg/outsider
byte-compiling build/bdist.linux-x86_64/egg/blackstarid/blackstarid.py to blackstarid.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/blackstarid/__init__.py to __init__.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/outsider/__main__.py to __main__.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/outsider/version.py to version.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/outsider/outsider.py to outsider.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/outsider/__init__.py to __init__.cpython-36.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying outsider.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying outsider.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying outsider.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying outsider.egg-info/entry_points.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying outsider.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying outsider.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
outsider.__pycache__.outsider.cpython-36: module references __file__
creating 'dist/outsider-0.1.0-py3.6.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing outsider-0.1.0-py3.6.egg
removing '/usr/local/lib/python3.6/dist-packages/outsider-0.1.0-py3.6.egg' (and everything under it)
creating /usr/local/lib/python3.6/dist-packages/outsider-0.1.0-py3.6.egg
Extracting outsider-0.1.0-py3.6.egg to /usr/local/lib/python3.6/dist-packages
outsider 0.1.0 is already the active version in easy-install.pth
Installing outsider script to /usr/local/bin

Installed /usr/local/lib/python3.6/dist-packages/outsider-0.1.0-py3.6.egg
Processing dependencies for outsider==0.1.0
Searching for pyusb==1.0.2
Best match: pyusb 1.0.2
Processing pyusb-1.0.2-py3.6.egg
pyusb 1.0.2 is already the active version in easy-install.pth

Using /usr/local/lib/python3.6/dist-packages/pyusb-1.0.2-py3.6.egg
Searching for PyQt5==5.11.3
Best match: PyQt5 5.11.3
Processing PyQt5-5.11.3-py3.6-linux-x86_64.egg
PyQt5 5.11.3 is already the active version in easy-install.pth
Installing pylupdate5 script to /usr/local/bin
Installing pyrcc5 script to /usr/local/bin
Installing pyuic5 script to /usr/local/bin

Using /usr/local/lib/python3.6/dist-packages/PyQt5-5.11.3-py3.6-linux-x86_64.egg
Searching for PyQt5-sip==4.19.13
Best match: PyQt5-sip 4.19.13
Processing PyQt5_sip-4.19.13-py3.6-linux-x86_64.egg
PyQt5-sip 4.19.13 is already the active version in easy-install.pth

Using /usr/local/lib/python3.6/dist-packages/PyQt5_sip-4.19.13-py3.6-linux-x86_64.egg
Finished processing dependencies for outsider==0.1.0

# outsider
Traceback (most recent call last):
  File "/usr/local/bin/outsider", line 11, in <module>
    load_entry_point('outsider==0.1.0', 'gui_scripts', 'outsider')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 480, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2693, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2324, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.6/dist-packages/outsider-0.1.0-py3.6.egg/outsider/__main__.py", line 18, in <module>
    from outsider.outsider import Ui
  File "/usr/local/lib/python3.6/dist-packages/outsider-0.1.0-py3.6.egg/outsider/outsider.py", line 19, in <module>
    from PyQt5.QtCore import QObject, QThread, QMutex
ModuleNotFoundError: No module named 'PyQt5.sip'

# pip3 freeze
asn1crypto==0.24.0
attrs==17.4.0
Automat==0.6.0
blinker==1.4
certifi==2018.1.18
chardet==3.0.4
click==6.7
cloud-init==18.4
colorama==0.3.7
command-not-found==0.3
configobj==5.0.6
constantly==15.1.0
cryptography==2.1.4
distro-info==0.18
httplib2==0.9.2
hyperlink==17.3.1
idna==2.6
incremental==16.10.1
Jinja2==2.10
jsonpatch==1.16
jsonpointer==1.10
jsonschema==2.6.0
keyring==10.6.0
keyrings.alt==3.0
language-selector==0.1
MarkupSafe==1.0
netifaces==0.10.4
oauthlib==2.0.6
outsider==0.1.0
PAM==0.4.2
pyasn1==0.4.2
pyasn1-modules==0.2.1
pycrypto==2.6.1
pygobject==3.26.1
PyJWT==1.5.3
pyOpenSSL==17.5.0
PyQt5==5.11.3
PyQt5-sip==4.19.13
pyserial==3.4
python-apt==1.6.3
python-debian==0.1.32
pyusb==1.0.2
pyxdg==0.25
PyYAML==3.12
requests==2.18.4
requests-unixsocket==0.1.5
SecretStorage==2.3.1
service-identity==16.0.0
six==1.11.0
ssh-import-id==5.7
systemd-python==234
Twisted==17.9.0
ufw==0.35
unattended-upgrades==0.1
urllib3==1.22
zope.interface==4.3.2

**Comment by magjo67** [comment]
I changed setup.py from:
install_requires=[
        'PyUSB',
        'PyQt5',
    ],
To
install_requires=[
        'PyUSB',
    ],

After that I installed support for pyqt5 via the Ubuntu repo.
Then the application worked.
