### ISSUE TITLE
how to install on ubuntu 16.04 

### ISSUE THREAD

**Issue by EndrII** [jonathanunderwood/outsider#9]
how to install on ubuntu 16.04 this program?
i built this program but i can't running this.<br>
`Traceback (most recent call last):
  File "/home/andrei/.local/bin/outsider", line 9, in <module>
    load_entry_point('outsider==0.0.2', 'gui_scripts', 'outsider')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2229, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/andrei/.local/lib/python3.5/site-packages/outsider-0.0.2-py3.5.egg/outsider/__main__.py", line 22, in <module>
    import blackstarid
  File "/home/andrei/.local/lib/python3.5/site-packages/outsider-0.0.2-py3.5.egg/blackstarid/__init__.py", line 18, in <module>
    from blackstarid import BlackstarIDAmp, NoDataAvailable, NotConnectedError
ImportError: cannot import name 'BlackstarIDAmp'
`

**Comment by EndrII** [comment]
????

**Comment by alcyde-rains** [comment]
same can't install : return of the install in a term :   File "setup.py", line 88, in <module>
    'outsider = outsider.__main__:main',
  File "/usr/lib/python3.5/distutils/core.py", line 108, in setup
    _setup_distribution = dist = klass(attrs)
  File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 272, in __init__
    _Distribution.__init__(self,attrs)
  File "/usr/lib/python3.5/distutils/dist.py", line 281, in __init__
    self.finalize_options()
  File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 327, in finalize_options
    ep.load()(self, ep.name, value)
  File "/home/patours/Téléchargements/outsider-master/.eggs/setuptools_scm-2.1.0-py3.5.egg/setuptools_scm/integration.py", line 22, in version_keyword
  File "/home/patours/Téléchargements/outsider-master/.eggs/setuptools_scm-2.1.0-py3.5.egg/setuptools_scm/__init__.py", line 119, in get_version
  File "/home/patours/Téléchargements/outsider-master/.eggs/setuptools_scm-2.1.0-py3.5.egg/setuptools_scm/__init__.py", line 97, in _do_parse
LookupError: setuptools-scm was unable to detect version for '/home/patours/Téléchargements/outsider-master'.

Make sure you're either building from a fully intact git repository or PyPI tarballs. Most other sources (such as GitHub's tarballs, a git checkout without the .git folder) don't contain the necessary metadata and will not work.

For example, if you're using pip, instead of https://github.com/user/proj/archive/master.zip use git+https://github.com/user/proj.git#egg=proj
don't know what else to do... :((

**Comment by EndrII** [comment]
add your app into pip, it is good solution for this problem
